# -*- coding:
# announcement_type = scrapy.Field() utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# http://doc.scrapy.org/en/latest/topics/items.html
import scrapy


class lossItem(scrapy.Item):
    file_name = scrapy.Field()
    file_path = scrapy.Field()
    doc_type = scrapy.Field()
    doc_source_url = scrapy.Field()
    gmt_create = scrapy.Field()
    user_create = scrapy.Field()
    gmt_update = scrapy.Field()
    user_update = scrapy.Field()
    report_id = scrapy.Field()
    doc_downloaded_timestamp = scrapy.Field()
    is_downloaded = scrapy.Field()


class ChinaIntroItem_sh_non(scrapy.Item):
    announcement_type = scrapy.Field()
    detail_type = scrapy.Field()
    file_name = scrapy.Field()
    file_path = scrapy.Field()
    # doc_source_url = scrapy.Field()

    country_code = scrapy.Field()
    exchange_market_code = scrapy.Field()
    company_code = scrapy.Field()
    fiscal_year = scrapy.Field()
    financial_statement_type_code = scrapy.Field()
    financial_statement_season_type_code = scrapy.Field()
    financial_reporting_standard_code = scrapy.Field()
    disclosure_date = scrapy.Field()
    start_date = scrapy.Field()
    end_date = scrapy.Field()
    language_written_code = scrapy.Field()
    doc_type = scrapy.Field()
    doc_source_url = scrapy.Field()
    is_doc_url_direct = scrapy.Field()
    doc_local_path = scrapy.Field()
    doc_downloaded_timestamp = scrapy.Field()
    is_downloaded = scrapy.Field()
    currency_code = scrapy.Field()
    is_consolidated = scrapy.Field()
    version = scrapy.Field()
    gmt_create = scrapy.Field()
    user_create = scrapy.Field()
    gmt_update = scrapy.Field()
    user_update = scrapy.Field()
    report_id = scrapy.Field()

    college_name = scrapy.Field()
    training_date = scrapy.Field()
    training_num = scrapy.Field()
    gender = scrapy.Field()
    age = scrapy.Field()
    education = scrapy.Field()
    discipline = scrapy.Field()
    job_title = scrapy.Field()
    recent_training_date = scrapy.Field()
    belong_2_type = scrapy.Field()
    punish_date = scrapy.Field()
    agency_name = scrapy.Field()
    agency_type = scrapy.Field()
    litigant = scrapy.Field()
    punish_type = scrapy.Field()
    release_sale_date = scrapy.Field()
    release_sale_shareholder_num = scrapy.Field()
    release_sale_stock_num = scrapy.Field()
    release_sale_stock_rate = scrapy.Field()
    shareholder_name = scrapy.Field()
    managed_member_name = scrapy.Field()
    bcpljcgf_num = scrapy.Field()
    bcpljcgf_rate = scrapy.Field()
    tgdzjyjc_num = scrapy.Field()
    tgdzjyjc_rate = scrapy.Field()
    jchrcygf_num = scrapy.Field()
    jchrcygf_rate = scrapy.Field()
    security_code = scrapy.Field()
    spiderName = scrapy.Field()

class ChinaIntroItem_sh(scrapy.Item):
    announcement_type = scrapy.Field()
    detail_type = scrapy.Field()
    file_name = scrapy.Field()
    file_path = scrapy.Field()
    #doc_source_url = scrapy.Field()

    country_code = scrapy.Field()
    exchange_market_code = scrapy.Field()
    company_code = scrapy.Field()
    fiscal_year = scrapy.Field()
    financial_statement_type_code = scrapy.Field()
    financial_statement_season_type_code = scrapy.Field()
    financial_reporting_standard_code = scrapy.Field()
    disclosure_date = scrapy.Field()
    start_date = scrapy.Field()
    end_date = scrapy.Field()
    language_written_code = scrapy.Field()
    doc_type = scrapy.Field()
    doc_source_url = scrapy.Field()
    is_doc_url_direct = scrapy.Field()
    doc_local_path = scrapy.Field()
    doc_downloaded_timestamp = scrapy.Field()
    is_downloaded = scrapy.Field()
    currency_code = scrapy.Field()
    is_consolidated = scrapy.Field()
    version = scrapy.Field()
    gmt_create = scrapy.Field()
    user_create = scrapy.Field()
    gmt_update = scrapy.Field()
    user_update = scrapy.Field()
    report_id = scrapy.Field()

    college_name = scrapy.Field()
    training_date = scrapy.Field()
    training_num = scrapy.Field()
    gender = scrapy.Field()
    age = scrapy.Field()
    education = scrapy.Field()
    discipline = scrapy.Field()
    job_title = scrapy.Field()
    recent_training_date = scrapy.Field()
    belong_2_type = scrapy.Field()
    punish_date = scrapy.Field()
    agency_name = scrapy.Field()
    agency_type = scrapy.Field()
    litigant = scrapy.Field()
    punish_type = scrapy.Field()
    release_sale_date = scrapy.Field()
    release_sale_shareholder_num = scrapy.Field()
    release_sale_stock_num = scrapy.Field()
    release_sale_stock_rate = scrapy.Field()
    shareholder_name = scrapy.Field()
    managed_member_name = scrapy.Field()
    bcpljcgf_num = scrapy.Field()
    bcpljcgf_rate = scrapy.Field()
    tgdzjyjc_num = scrapy.Field()
    tgdzjyjc_rate = scrapy.Field()
    jchrcygf_num = scrapy.Field()
    jchrcygf_rate = scrapy.Field()
    security_code = scrapy.Field()
    spiderName = scrapy.Field()


class ChinaIntroItem_ad(scrapy.Item):
    announcement_type = scrapy.Field()
    file_name = scrapy.Field()
    file_path = scrapy.Field()
    #doc_source_url = scrapy.Field()

    country_code = scrapy.Field()
    exchange_market_code = scrapy.Field()
    company_code = scrapy.Field()
    fiscal_year = scrapy.Field()
    financial_statement_type_code = scrapy.Field()
    financial_statement_season_type_code = scrapy.Field()
    financial_reporting_standard_code = scrapy.Field()
    disclosure_date = scrapy.Field()
    start_date = scrapy.Field()
    end_date = scrapy.Field()
    language_written_code = scrapy.Field()
    doc_type = scrapy.Field()
    doc_source_url = scrapy.Field()
    is_doc_url_direct = scrapy.Field()
    doc_local_path = scrapy.Field()
    doc_downloaded_timestamp = scrapy.Field()
    is_downloaded = scrapy.Field()
    currency_code = scrapy.Field()
    is_consolidated = scrapy.Field()
    version = scrapy.Field()
    gmt_create = scrapy.Field()
    user_create = scrapy.Field()
    gmt_update = scrapy.Field()
    user_update = scrapy.Field()
    report_id = scrapy.Field()

    college_name = scrapy.Field()
    training_date = scrapy.Field()
    training_num = scrapy.Field()
    gender = scrapy.Field()
    age = scrapy.Field()
    education = scrapy.Field()
    discipline = scrapy.Field()
    job_title = scrapy.Field()
    recent_training_date = scrapy.Field()
    belong_2_type = scrapy.Field()
    punish_date = scrapy.Field()
    agency_name = scrapy.Field()
    agency_type = scrapy.Field()
    litigant = scrapy.Field()
    punish_type = scrapy.Field()
    release_sale_date = scrapy.Field()
    release_sale_shareholder_num = scrapy.Field()
    release_sale_stock_num = scrapy.Field()
    release_sale_stock_rate = scrapy.Field()
    shareholder_name = scrapy.Field()
    managed_member_name = scrapy.Field()
    bcpljcgf_num = scrapy.Field()
    bcpljcgf_rate = scrapy.Field()
    tgdzjyjc_num = scrapy.Field()
    tgdzjyjc_rate = scrapy.Field()
    jchrcygf_num = scrapy.Field()
    jchrcygf_rate = scrapy.Field()
    security_code = scrapy.Field()
    spiderName = scrapy.Field()
    detail_type = scrapy.Field()


class ChinaIntroItem_cs(scrapy.Item):
    announcement_type = scrapy.Field()
    file_name = scrapy.Field()
    file_path = scrapy.Field()
    #doc_source_url = scrapy.Field()

    country_code = scrapy.Field()
    exchange_market_code = scrapy.Field()
    company_code = scrapy.Field()
    fiscal_year = scrapy.Field()
    financial_statement_type_code = scrapy.Field()
    financial_statement_season_type_code = scrapy.Field()
    financial_reporting_standard_code = scrapy.Field()
    disclosure_date = scrapy.Field()
    start_date = scrapy.Field()
    end_date = scrapy.Field()
    language_written_code = scrapy.Field()
    doc_type = scrapy.Field()
    doc_source_url = scrapy.Field()
    is_doc_url_direct = scrapy.Field()
    doc_local_path = scrapy.Field()
    doc_downloaded_timestamp = scrapy.Field()
    is_downloaded = scrapy.Field()
    currency_code = scrapy.Field()
    is_consolidated = scrapy.Field()
    version = scrapy.Field()
    gmt_create = scrapy.Field()
    user_create = scrapy.Field()
    gmt_update = scrapy.Field()
    user_update = scrapy.Field()
    report_id = scrapy.Field()

    college_name = scrapy.Field()
    training_date = scrapy.Field()
    training_num = scrapy.Field()
    gender = scrapy.Field()
    age = scrapy.Field()
    education = scrapy.Field()
    discipline = scrapy.Field()
    job_title = scrapy.Field()
    recent_training_date = scrapy.Field()
    belong_2_type = scrapy.Field()
    punish_date = scrapy.Field()
    agency_name = scrapy.Field()
    agency_type = scrapy.Field()
    litigant = scrapy.Field()
    punish_type = scrapy.Field()
    release_sale_date = scrapy.Field()
    release_sale_shareholder_num = scrapy.Field()
    release_sale_stock_num = scrapy.Field()
    release_sale_stock_rate = scrapy.Field()
    shareholder_name = scrapy.Field()
    managed_member_name = scrapy.Field()
    bcpljcgf_num = scrapy.Field()
    bcpljcgf_rate = scrapy.Field()
    tgdzjyjc_num = scrapy.Field()
    tgdzjyjc_rate = scrapy.Field()
    jchrcygf_num = scrapy.Field()
    jchrcygf_rate = scrapy.Field()
    security_code = scrapy.Field()
    spiderName = scrapy.Field()


class ChinaIntroItem_dsn(scrapy.Item):
    announcement_type = scrapy.Field()
    detail_type = scrapy.Field()
    file_name = scrapy.Field()
    file_path = scrapy.Field()
    #doc_source_url = scrapy.Field()

    country_code = scrapy.Field()
    exchange_market_code = scrapy.Field()
    company_code = scrapy.Field()
    fiscal_year = scrapy.Field()
    financial_statement_type_code = scrapy.Field()
    financial_statement_season_type_code = scrapy.Field()
    financial_reporting_standard_code = scrapy.Field()
    disclosure_date = scrapy.Field()
    start_date = scrapy.Field()
    end_date = scrapy.Field()
    language_written_code = scrapy.Field()
    doc_type = scrapy.Field()
    doc_source_url = scrapy.Field()
    is_doc_url_direct = scrapy.Field()
    doc_local_path = scrapy.Field()
    doc_downloaded_timestamp = scrapy.Field()
    is_downloaded = scrapy.Field()
    currency_code = scrapy.Field()
    is_consolidated = scrapy.Field()
    version = scrapy.Field()
    gmt_create = scrapy.Field()
    user_create = scrapy.Field()
    gmt_update = scrapy.Field()
    user_update = scrapy.Field()
    report_id = scrapy.Field()

    college_name = scrapy.Field()
    training_date = scrapy.Field()
    training_num = scrapy.Field()
    gender = scrapy.Field()
    age = scrapy.Field()
    education = scrapy.Field()
    discipline = scrapy.Field()
    job_title = scrapy.Field()
    recent_training_date = scrapy.Field()
    belong_2_type = scrapy.Field()
    punish_date = scrapy.Field()
    agency_name = scrapy.Field()
    agency_type = scrapy.Field()
    litigant = scrapy.Field()
    punish_type = scrapy.Field()
    release_sale_date = scrapy.Field()
    release_sale_shareholder_num = scrapy.Field()
    release_sale_stock_num = scrapy.Field()
    release_sale_stock_rate = scrapy.Field()
    shareholder_name = scrapy.Field()
    managed_member_name = scrapy.Field()
    bcpljcgf_num = scrapy.Field()
    bcpljcgf_rate = scrapy.Field()
    tgdzjyjc_num = scrapy.Field()
    tgdzjyjc_rate = scrapy.Field()
    jchrcygf_num = scrapy.Field()
    jchrcygf_rate = scrapy.Field()
    security_code = scrapy.Field()
    spiderName = scrapy.Field()


class ChinaIntroItem_if(scrapy.Item):
    announcement_type = scrapy.Field()
    file_name = scrapy.Field()
    file_path = scrapy.Field()
    #doc_source_url = scrapy.Field()

    country_code = scrapy.Field()
    exchange_market_code = scrapy.Field()
    company_code = scrapy.Field()
    fiscal_year = scrapy.Field()
    financial_statement_type_code = scrapy.Field()
    financial_statement_season_type_code = scrapy.Field()
    financial_reporting_standard_code = scrapy.Field()
    disclosure_date = scrapy.Field()
    start_date = scrapy.Field()
    end_date = scrapy.Field()
    language_written_code = scrapy.Field()
    doc_type = scrapy.Field()
    doc_source_url = scrapy.Field()
    is_doc_url_direct = scrapy.Field()
    doc_local_path = scrapy.Field()
    doc_downloaded_timestamp = scrapy.Field()
    is_downloaded = scrapy.Field()
    currency_code = scrapy.Field()
    is_consolidated = scrapy.Field()
    version = scrapy.Field()
    gmt_create = scrapy.Field()
    user_create = scrapy.Field()
    gmt_update = scrapy.Field()
    user_update = scrapy.Field()
    report_id = scrapy.Field()

    college_name = scrapy.Field()
    training_date = scrapy.Field()
    training_num = scrapy.Field()
    gender = scrapy.Field()
    age = scrapy.Field()
    education = scrapy.Field()
    discipline = scrapy.Field()
    job_title = scrapy.Field()
    recent_training_date = scrapy.Field()
    belong_2_type = scrapy.Field()
    punish_date = scrapy.Field()
    agency_name = scrapy.Field()
    agency_type = scrapy.Field()
    litigant = scrapy.Field()
    punish_type = scrapy.Field()
    release_sale_date = scrapy.Field()
    release_sale_shareholder_num = scrapy.Field()
    release_sale_stock_num = scrapy.Field()
    release_sale_stock_rate = scrapy.Field()
    shareholder_name = scrapy.Field()
    managed_member_name = scrapy.Field()
    bcpljcgf_num = scrapy.Field()
    bcpljcgf_rate = scrapy.Field()
    tgdzjyjc_num = scrapy.Field()
    tgdzjyjc_rate = scrapy.Field()
    jchrcygf_num = scrapy.Field()
    jchrcygf_rate = scrapy.Field()
    security_code = scrapy.Field()
    spiderName = scrapy.Field()


class ChinaIntroItem_si(scrapy.Item):
    secretary_name = scrapy.Field()
    announcement_type = scrapy.Field()
    file_name = scrapy.Field()
    file_path = scrapy.Field()
    #doc_source_url = scrapy.Field()

    country_code = scrapy.Field()
    exchange_market_code = scrapy.Field()
    company_code = scrapy.Field()
    fiscal_year = scrapy.Field()
    financial_statement_type_code = scrapy.Field()
    financial_statement_season_type_code = scrapy.Field()
    financial_reporting_standard_code = scrapy.Field()
    disclosure_date = scrapy.Field()
    start_date = scrapy.Field()
    end_date = scrapy.Field()
    language_written_code = scrapy.Field()
    doc_type = scrapy.Field()
    doc_source_url = scrapy.Field()
    is_doc_url_direct = scrapy.Field()
    doc_local_path = scrapy.Field()
    doc_downloaded_timestamp = scrapy.Field()
    is_downloaded = scrapy.Field()
    currency_code = scrapy.Field()
    is_consolidated = scrapy.Field()
    version = scrapy.Field()
    gmt_create = scrapy.Field()
    user_create = scrapy.Field()
    gmt_update = scrapy.Field()
    user_update = scrapy.Field()
    report_id = scrapy.Field()

    college_name = scrapy.Field()
    training_date = scrapy.Field()
    training_num = scrapy.Field()
    gender = scrapy.Field()
    age = scrapy.Field()
    education = scrapy.Field()
    discipline = scrapy.Field()
    job_title = scrapy.Field()
    recent_training_date = scrapy.Field()
    belong_2_type = scrapy.Field()
    punish_date = scrapy.Field()
    agency_name = scrapy.Field()
    agency_type = scrapy.Field()
    litigant = scrapy.Field()
    punish_type = scrapy.Field()
    release_sale_date = scrapy.Field()
    release_sale_shareholder_num = scrapy.Field()
    release_sale_stock_num = scrapy.Field()
    release_sale_stock_rate = scrapy.Field()
    shareholder_name = scrapy.Field()
    managed_member_name = scrapy.Field()
    bcpljcgf_num = scrapy.Field()
    bcpljcgf_rate = scrapy.Field()
    tgdzjyjc_num = scrapy.Field()
    tgdzjyjc_rate = scrapy.Field()
    jchrcygf_num = scrapy.Field()
    jchrcygf_rate = scrapy.Field()
    security_code = scrapy.Field()
    spiderName = scrapy.Field()


class ChinaIntroItem_str(scrapy.Item):
    secretary_name = scrapy.Field()
    announcement_type = scrapy.Field()
    file_name = scrapy.Field()
    file_path = scrapy.Field()
    #doc_source_url = scrapy.Field()

    country_code = scrapy.Field()
    exchange_market_code = scrapy.Field()
    company_code = scrapy.Field()
    fiscal_year = scrapy.Field()
    financial_statement_type_code = scrapy.Field()
    financial_statement_season_type_code = scrapy.Field()
    financial_reporting_standard_code = scrapy.Field()
    disclosure_date = scrapy.Field()
    start_date = scrapy.Field()
    end_date = scrapy.Field()
    language_written_code = scrapy.Field()
    doc_type = scrapy.Field()
    doc_source_url = scrapy.Field()
    is_doc_url_direct = scrapy.Field()
    doc_local_path = scrapy.Field()
    doc_downloaded_timestamp = scrapy.Field()
    is_downloaded = scrapy.Field()
    currency_code = scrapy.Field()
    is_consolidated = scrapy.Field()
    version = scrapy.Field()
    gmt_create = scrapy.Field()
    user_create = scrapy.Field()
    gmt_update = scrapy.Field()
    user_update = scrapy.Field()
    report_id = scrapy.Field()

    college_name = scrapy.Field()
    training_date = scrapy.Field()
    training_num = scrapy.Field()
    gender = scrapy.Field()
    age = scrapy.Field()
    education = scrapy.Field()
    discipline = scrapy.Field()
    job_title = scrapy.Field()
    recent_training_date = scrapy.Field()
    belong_2_type = scrapy.Field()
    punish_date = scrapy.Field()
    agency_name = scrapy.Field()
    agency_type = scrapy.Field()
    litigant = scrapy.Field()
    punish_type = scrapy.Field()
    release_sale_date = scrapy.Field()
    release_sale_shareholder_num = scrapy.Field()
    release_sale_stock_num = scrapy.Field()
    release_sale_stock_rate = scrapy.Field()
    shareholder_name = scrapy.Field()
    managed_member_name = scrapy.Field()
    bcpljcgf_num = scrapy.Field()
    bcpljcgf_rate = scrapy.Field()
    tgdzjyjc_num = scrapy.Field()
    tgdzjyjc_rate = scrapy.Field()
    jchrcygf_num = scrapy.Field()
    jchrcygf_rate = scrapy.Field()
    security_code = scrapy.Field()
    spiderName = scrapy.Field()


class ChinaIntroItem_sbi(scrapy.Item):
    announcement_type = scrapy.Field()
    file_name = scrapy.Field()
    file_path = scrapy.Field()
    #doc_source_url = scrapy.Field()

    country_code = scrapy.Field()
    exchange_market_code = scrapy.Field()
    company_code = scrapy.Field()
    fiscal_year = scrapy.Field()
    financial_statement_type_code = scrapy.Field()
    financial_statement_season_type_code = scrapy.Field()
    financial_reporting_standard_code = scrapy.Field()
    disclosure_date = scrapy.Field()
    start_date = scrapy.Field()
    end_date = scrapy.Field()
    language_written_code = scrapy.Field()
    doc_type = scrapy.Field()
    doc_source_url = scrapy.Field()
    is_doc_url_direct = scrapy.Field()
    doc_local_path = scrapy.Field()
    doc_downloaded_timestamp = scrapy.Field()
    is_downloaded = scrapy.Field()
    currency_code = scrapy.Field()
    is_consolidated = scrapy.Field()
    version = scrapy.Field()
    gmt_create = scrapy.Field()
    user_create = scrapy.Field()
    gmt_update = scrapy.Field()
    user_update = scrapy.Field()
    report_id = scrapy.Field()

    college_name = scrapy.Field()
    training_date = scrapy.Field()
    training_num = scrapy.Field()
    gender = scrapy.Field()
    age = scrapy.Field()
    education = scrapy.Field()
    discipline = scrapy.Field()
    job_title = scrapy.Field()
    recent_training_date = scrapy.Field()
    belong_2_type = scrapy.Field()
    punish_date = scrapy.Field()
    agency_name = scrapy.Field()
    agency_type = scrapy.Field()
    litigant = scrapy.Field()
    punish_type = scrapy.Field()
    release_sale_date = scrapy.Field()
    release_sale_shareholder_num = scrapy.Field()
    release_sale_stock_num = scrapy.Field()
    release_sale_stock_rate = scrapy.Field()
    shareholder_name = scrapy.Field()
    managed_member_name = scrapy.Field()
    bcpljcgf_num = scrapy.Field()
    bcpljcgf_rate = scrapy.Field()
    tgdzjyjc_num = scrapy.Field()
    tgdzjyjc_rate = scrapy.Field()
    jchrcygf_num = scrapy.Field()
    jchrcygf_rate = scrapy.Field()
    security_code = scrapy.Field()
    spiderName = scrapy.Field()


class ChinaIntroItem_stp(scrapy.Item):
    announcement_type = scrapy.Field()
    file_name = scrapy.Field()
    file_path = scrapy.Field()
    #doc_source_url = scrapy.Field()

    country_code = scrapy.Field()
    exchange_market_code = scrapy.Field()
    company_code = scrapy.Field()
    fiscal_year = scrapy.Field()
    financial_statement_type_code = scrapy.Field()
    financial_statement_season_type_code = scrapy.Field()
    financial_reporting_standard_code = scrapy.Field()
    disclosure_date = scrapy.Field()
    start_date = scrapy.Field()
    end_date = scrapy.Field()
    language_written_code = scrapy.Field()
    doc_type = scrapy.Field()
    doc_source_url = scrapy.Field()
    is_doc_url_direct = scrapy.Field()
    doc_local_path = scrapy.Field()
    doc_downloaded_timestamp = scrapy.Field()
    is_downloaded = scrapy.Field()
    currency_code = scrapy.Field()
    is_consolidated = scrapy.Field()
    version = scrapy.Field()
    gmt_create = scrapy.Field()
    user_create = scrapy.Field()
    gmt_update = scrapy.Field()
    user_update = scrapy.Field()
    report_id = scrapy.Field()

    college_name = scrapy.Field()
    training_date = scrapy.Field()
    training_num = scrapy.Field()
    gender = scrapy.Field()
    age = scrapy.Field()
    education = scrapy.Field()
    discipline = scrapy.Field()
    job_title = scrapy.Field()
    recent_training_date = scrapy.Field()
    belong_2_type = scrapy.Field()
    punish_date = scrapy.Field()
    agency_name = scrapy.Field()
    agency_type = scrapy.Field()
    litigant = scrapy.Field()
    punish_type = scrapy.Field()
    release_sale_date = scrapy.Field()
    release_sale_shareholder_num = scrapy.Field()
    release_sale_stock_num = scrapy.Field()
    release_sale_stock_rate = scrapy.Field()
    shareholder_name = scrapy.Field()
    managed_member_name = scrapy.Field()
    bcpljcgf_num = scrapy.Field()
    bcpljcgf_rate = scrapy.Field()
    tgdzjyjc_num = scrapy.Field()
    tgdzjyjc_rate = scrapy.Field()
    jchrcygf_num = scrapy.Field()
    jchrcygf_rate = scrapy.Field()
    security_code = scrapy.Field()
    spiderName = scrapy.Field()


class ChinaIntroItem_xsg(scrapy.Item):
    announcement_type = scrapy.Field()
    file_name = scrapy.Field()
    file_path = scrapy.Field()
    #doc_source_url = scrapy.Field()

    country_code = scrapy.Field()
    exchange_market_code = scrapy.Field()
    company_code = scrapy.Field()
    fiscal_year = scrapy.Field()
    financial_statement_type_code = scrapy.Field()
    financial_statement_season_type_code = scrapy.Field()
    financial_reporting_standard_code = scrapy.Field()
    disclosure_date = scrapy.Field()
    start_date = scrapy.Field()
    end_date = scrapy.Field()
    language_written_code = scrapy.Field()
    doc_type = scrapy.Field()
    doc_source_url = scrapy.Field()
    is_doc_url_direct = scrapy.Field()
    doc_local_path = scrapy.Field()
    doc_downloaded_timestamp = scrapy.Field()
    is_downloaded = scrapy.Field()
    currency_code = scrapy.Field()
    is_consolidated = scrapy.Field()
    version = scrapy.Field()
    gmt_create = scrapy.Field()
    user_create = scrapy.Field()
    gmt_update = scrapy.Field()
    user_update = scrapy.Field()
    report_id = scrapy.Field()

    college_name = scrapy.Field()
    training_date = scrapy.Field()
    training_num = scrapy.Field()
    gender = scrapy.Field()
    age = scrapy.Field()
    education = scrapy.Field()
    discipline = scrapy.Field()
    job_title = scrapy.Field()
    recent_training_date = scrapy.Field()
    belong_2_type = scrapy.Field()
    punish_date = scrapy.Field()
    agency_name = scrapy.Field()
    agency_type = scrapy.Field()
    litigant = scrapy.Field()
    punish_type = scrapy.Field()
    release_sale_date = scrapy.Field()
    release_sale_shareholder_num = scrapy.Field()
    release_sale_stock_num = scrapy.Field()
    release_sale_stock_rate = scrapy.Field()
    shareholder_name = scrapy.Field()
    managed_member_name = scrapy.Field()
    bcpljcgf_num = scrapy.Field()
    bcpljcgf_rate = scrapy.Field()
    tgdzjyjc_num = scrapy.Field()
    tgdzjyjc_rate = scrapy.Field()
    jchrcygf_num = scrapy.Field()
    jchrcygf_rate = scrapy.Field()
    security_code = scrapy.Field()
    spiderName = scrapy.Field()


class ChinaIntroItem_dd(scrapy.Item):
    announcement_type = scrapy.Field()
    file_name = scrapy.Field()
    file_path = scrapy.Field()
    #doc_source_url = scrapy.Field()

    country_code = scrapy.Field()
    exchange_market_code = scrapy.Field()
    company_code = scrapy.Field()
    fiscal_year = scrapy.Field()
    financial_statement_type_code = scrapy.Field()
    financial_statement_season_type_code = scrapy.Field()
    financial_reporting_standard_code = scrapy.Field()
    disclosure_date = scrapy.Field()
    start_date = scrapy.Field()
    end_date = scrapy.Field()
    language_written_code = scrapy.Field()
    doc_type = scrapy.Field()
    doc_source_url = scrapy.Field()
    is_doc_url_direct = scrapy.Field()
    doc_local_path = scrapy.Field()
    doc_downloaded_timestamp = scrapy.Field()
    is_downloaded = scrapy.Field()
    currency_code = scrapy.Field()
    is_consolidated = scrapy.Field()
    version = scrapy.Field()
    gmt_create = scrapy.Field()
    user_create = scrapy.Field()
    gmt_update = scrapy.Field()
    user_update = scrapy.Field()
    report_id = scrapy.Field()

    college_name = scrapy.Field()
    training_date = scrapy.Field()
    training_num = scrapy.Field()
    gender = scrapy.Field()
    age = scrapy.Field()
    education = scrapy.Field()
    discipline = scrapy.Field()
    job_title = scrapy.Field()
    recent_training_date = scrapy.Field()
    belong_2_type = scrapy.Field()
    punish_date = scrapy.Field()
    agency_name = scrapy.Field()
    agency_type = scrapy.Field()
    litigant = scrapy.Field()
    punish_type = scrapy.Field()
    release_sale_date = scrapy.Field()
    release_sale_shareholder_num = scrapy.Field()
    release_sale_stock_num = scrapy.Field()
    release_sale_stock_rate = scrapy.Field()
    shareholder_name = scrapy.Field()
    managed_member_name = scrapy.Field()
    bcpljcgf_num = scrapy.Field()
    bcpljcgf_rate = scrapy.Field()
    tgdzjyjc_num = scrapy.Field()
    tgdzjyjc_rate = scrapy.Field()
    jchrcygf_num = scrapy.Field()
    jchrcygf_rate = scrapy.Field()
    security_code = scrapy.Field()
    spiderName = scrapy.Field()


class ChinaIntroItem_shanghai(scrapy.Item):
    file_name = scrapy.Field()
    file_path = scrapy.Field()
    doc_source_url = scrapy.Field()
    company_name = scrapy.Field()
    company_code = scrapy.Field()

    # company item
    code = scrapy.Field()
    name_origin = scrapy.Field()
    name_en = scrapy.Field()
    security_code = scrapy.Field()
    country_code_listed = scrapy.Field()
    country_code_origin = scrapy.Field()
    exchange_market_code = scrapy.Field()
    ipo_date = scrapy.Field()
    currency_code = scrapy.Field()
    status = scrapy.Field()
    website_url = scrapy.Field()
    gmt_create = scrapy.Field()
    user_create = scrapy.Field()

    # detail item_value_shanghai
    company_short_name_zh = scrapy.Field()
    company_short_name_en = scrapy.Field()
    registered_address = scrapy.Field()
    mailing_address = scrapy.Field()
    legal_representative = scrapy.Field()
    secretary_name = scrapy.Field()
    e_mail = scrapy.Field()
    phone_number = scrapy.Field()
    CSRC_industry = scrapy.Field()
    SSE_industry = scrapy.Field()
    district_belong_to = scrapy.Field()
    is_SSE_180_sample_stock = scrapy.Field()
    is_overseas_listing = scrapy.Field()
    overseas_listing_land = scrapy.Field()
    convertible_bonds_for_short = scrapy.Field()
    # detail item_title_shanghai
    company_short_name_zh_title = scrapy.Field()
    company_short_name_en_title = scrapy.Field()
    registered_address_title = scrapy.Field()
    mailing_address_title = scrapy.Field()
    legal_representative_title = scrapy.Field()
    secretary_name_title = scrapy.Field()
    e_mail_title = scrapy.Field()
    phone_number_title = scrapy.Field()
    CSRC_industry_title = scrapy.Field()
    SSE_industry_title = scrapy.Field()
    district_belong_to_title = scrapy.Field()
    is_SSE_180_sample_stock_title = scrapy.Field()
    is_overseas_listing_title = scrapy.Field()
    overseas_listing_land_title = scrapy.Field()
    convertible_bonds_for_short_title = scrapy.Field()

    # detail item title shenzhen
    industry_title = scrapy.Field()
    Total_share_capital_of_A_shares_title = scrapy.Field()
    A_shares_circulating_capital_title = scrapy.Field()
    industry = scrapy.Field()
    Total_share_capital_of_A_shares = scrapy.Field()
    A_shares_circulating_capital = scrapy.Field()


class ChinaIntroItem_shenzhen(scrapy.Item):
    file_name = scrapy.Field()
    file_path = scrapy.Field()
    doc_source_url = scrapy.Field()
    company_name = scrapy.Field()
    company_code = scrapy.Field()

    # company item
    code = scrapy.Field()
    name_origin = scrapy.Field()
    name_en = scrapy.Field()
    security_code = scrapy.Field()
    country_code_listed = scrapy.Field()
    country_code_origin = scrapy.Field()
    exchange_market_code = scrapy.Field()
    ipo_date = scrapy.Field()
    currency_code = scrapy.Field()
    status = scrapy.Field()
    website_url = scrapy.Field()
    gmt_create = scrapy.Field()
    user_create = scrapy.Field()

    # detail item_value_shanghai
    company_short_name_zh = scrapy.Field()
    company_short_name_en = scrapy.Field()
    registered_address = scrapy.Field()
    mailing_address = scrapy.Field()
    legal_representative = scrapy.Field()
    secretary_name = scrapy.Field()
    e_mail = scrapy.Field()
    phone_number = scrapy.Field()
    CSRC_industry = scrapy.Field()
    SSE_industry = scrapy.Field()
    district_belong_to = scrapy.Field()
    is_SSE_180_sample_stock = scrapy.Field()
    is_overseas_listing = scrapy.Field()
    overseas_listing_land = scrapy.Field()
    convertible_bonds_for_short = scrapy.Field()
    # detail item_title_shanghai
    company_short_name_zh_title = scrapy.Field()
    company_short_name_en_title = scrapy.Field()
    registered_address_title = scrapy.Field()
    mailing_address_title = scrapy.Field()
    legal_representative_title = scrapy.Field()
    secretary_name_title = scrapy.Field()
    e_mail_title = scrapy.Field()
    phone_number_title = scrapy.Field()
    CSRC_industry_title = scrapy.Field()
    SSE_industry_title = scrapy.Field()
    district_belong_to_title = scrapy.Field()
    is_SSE_180_sample_stock_title = scrapy.Field()
    is_overseas_listing_title = scrapy.Field()
    overseas_listing_land_title = scrapy.Field()
    convertible_bonds_for_short_title = scrapy.Field()

    # detail item title shenzhen
    industry_title = scrapy.Field()
    Total_share_capital_of_A_shares_title = scrapy.Field()
    A_shares_circulating_capital_title = scrapy.Field()
    industry = scrapy.Field()
    Total_share_capital_of_A_shares = scrapy.Field()
    A_shares_circulating_capital = scrapy.Field()


class ChinaIntroItem_shenzhenL(scrapy.Item):
    plate_type = scrapy.Field()
    code = scrapy.Field()
    company_short_name_zh = scrapy.Field()
    name_origin = scrapy.Field()
    security_code = scrapy.Field()
    website_url = scrapy.Field()
    gmt_create = scrapy.Field()
    user_create = scrapy.Field()
    doc_source_url = scrapy.Field()


class ChinaIntroItem_shenzhen_status(scrapy.Item):
    ipo_date = scrapy.Field()
    code = scrapy.Field()
    end_date = scrapy.Field()
    gmt_update = scrapy.Field()
    user_create = scrapy.Field()
    doc_source_url = scrapy.Field()
    status = scrapy.Field()
    exchange_market_code = scrapy.Field()


class ChinaIntroItem_shenzhen_nameChange(scrapy.Item):
    end_date = scrapy.Field()
    code = scrapy.Field()
    fomer_name = scrapy.Field()
    gmt_create = scrapy.Field()
    user_create = scrapy.Field()
    doc_source_url = scrapy.Field()


class ChinaIntroItem_shanghaiL(scrapy.Item):
    data = scrapy.Field()
    doc_source_url = scrapy.Field()