# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# http://doc.scrapy.org/en/latest/topics/items.html

import scrapy


class AustraliacompanyupdateItem(scrapy.Item):
    pdf_name = scrapy.Field()
    pdf_path = scrapy.Field()
    doc_source_url = scrapy.Field()

    # DownloadPdf items
    country_code = scrapy.Field()
    exchange_market_code = scrapy.Field()
    company_code = scrapy.Field()
    financial_statement_season_type_code = scrapy.Field()
    financial_reporting_standard_code = scrapy.Field()
    disclosure_date = scrapy.Field()
    language_written_code = scrapy.Field()
    doc_type = scrapy.Field()
    is_doc_url_direct = scrapy.Field()
    doc_local_path = scrapy.Field()
    doc_downloaded_timestamp = scrapy.Field()
    is_downloaded = scrapy.Field()
    currency_code = scrapy.Field()
    gmt_create = scrapy.Field()
    user_create = scrapy.Field()
    fiscal_year = scrapy.Field()
    report_id = scrapy.Field()
    announcement_type = scrapy.Field()
    original_title = scrapy.Field()

    #Info items
    Title = scrapy.Field()
    Description_title = scrapy.Field()
    Security_code = scrapy.Field()
    Issuer_code_title = scrapy.Field()
    Official_listing_date = scrapy.Field()
    Listing_Date = scrapy.Field()
    Fiscal_year_title = scrapy.Field()
    GICS_industry_group_title = scrapy.Field()
    Exempt_foreigb_title = scrapy.Field()
    Internet_address = scrapy.Field()
    Registered_office_address_title = scrapy.Field()
    Head_office_telephone_title = scrapy.Field()
    Head_office_fax_title = scrapy.Field()
    Share_registry_title = scrapy.Field()
    Share_registry_telephone_title = scrapy.Field()
    Message_title = scrapy.Field()
    ACN_ARBN = scrapy.Field()
    NSX_CODE = scrapy.Field()
    NSX_LISTED_SECURITIES = scrapy.Field()
    LISTING_DATE = scrapy.Field()
    PRINCIPAL_ACTIVITIES = scrapy.Field()
    INDUSTRY_CLASS = scrapy.Field()
    STREET_ADDRESS = scrapy.Field()
    COMPANY_BASE = scrapy.Field()
    WEB = scrapy.Field()
    EMAIL = scrapy.Field()
    PHONE = scrapy.Field()
    FAX = scrapy.Field()
    SOLICITORS = scrapy.Field()
    NOMINATED_ADVISERS = scrapy.Field()
    AUDITOR = scrapy.Field()
    BALANCE_DATE = scrapy.Field()
    TRADING_CODE = scrapy.Field()
    ISIN = scrapy.Field()
    FIGI = scrapy.Field()
    BLOOMBERG_TICKER = scrapy.Field()
    SECUTITY_DESCRIPTION = scrapy.Field()
    SECUTITY_TYPE = scrapy.Field()
    CERTIFICATED = scrapy.Field()
    SETTLEMENT = scrapy.Field()
    SECURITY_STATUS = scrapy.Field()
    STARTED_TRADING_ON = scrapy.Field()
    PREVIOUS_SECUTITY_CODES = scrapy.Field()
    PERVIOUS_SECURITY_EFFECYIVE_DATES = scrapy.Field()
    TOTAL_SECUTYIES_ISSUED_IN_THIS_CLASS = scrapy.Field()
    LISTING_PRICE = scrapy.Field()
    ORIGINAL_OFFER_DOCUMENT = scrapy.Field()
    ANNOUNCEMENTS = scrapy.Field()
    POSTAL_ADDRESS = scrapy.Field()
    Management_title = scrapy.Field()

    # company item
    company_id = scrapy.Field()
    code = scrapy.Field()
    name_origin = scrapy.Field()
    name_en = scrapy.Field()
    security_code = scrapy.Field()
    country_code_listed = scrapy.Field()
    country_code_origin = scrapy.Field()
    ipo_date = scrapy.Field()
    status = scrapy.Field()
    website_url = scrapy.Field()


class AustraliacompanyupdateNSXItem(scrapy.Item):
    pdf_name = scrapy.Field()
    pdf_path = scrapy.Field()
    doc_source_url = scrapy.Field()

    # DownloadPdf items
    country_code = scrapy.Field()
    exchange_market_code = scrapy.Field()
    company_code = scrapy.Field()
    financial_statement_season_type_code = scrapy.Field()
    financial_reporting_standard_code = scrapy.Field()
    disclosure_date = scrapy.Field()
    language_written_code = scrapy.Field()
    doc_type = scrapy.Field()
    is_doc_url_direct = scrapy.Field()
    doc_local_path = scrapy.Field()
    doc_downloaded_timestamp = scrapy.Field()
    is_downloaded = scrapy.Field()
    currency_code = scrapy.Field()
    gmt_create = scrapy.Field()
    user_create = scrapy.Field()
    fiscal_year = scrapy.Field()
    report_id = scrapy.Field()
    announcement_type = scrapy.Field()
    original_title = scrapy.Field()