# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# http://doc.scrapy.org/en/latest/topics/items.html

import scrapy


class ShenzhensecuritiesItem(scrapy.Item):
    file_name = scrapy.Field()
    file_path = scrapy.Field()
    country_code = scrapy.Field()
    report_id = scrapy.Field()
    announcement_type = scrapy.Field()
    exchange_market_code = scrapy.Field()
    company_code = scrapy.Field()
    fiscal_year = scrapy.Field()
    financial_statement_type_code = scrapy.Field()
    financial_statement_season_type_code = scrapy.Field()
    financial_reporting_standard_code = scrapy.Field()
    disclosure_date = scrapy.Field()
    start_date = scrapy.Field()
    end_date = scrapy.Field()
    language_written_code = scrapy.Field()
    doc_type = scrapy.Field()
    doc_source_url = scrapy.Field()
    is_doc_url_direct = scrapy.Field()
    doc_local_path = scrapy.Field()
    doc_downloaded_timestamp = scrapy.Field()
    is_downloaded = scrapy.Field()
    currency_code = scrapy.Field()
    is_consolidated = scrapy.Field()
    version = scrapy.Field()
    gmt_create = scrapy.Field()
    user_create = scrapy.Field()
    detail_type = scrapy.Field()
    pdf_name = scrapy.Field()
    company_id = scrapy.Field()
    bond_short_name = scrapy.Field()


class ShenzhensecuritiesItemOther(scrapy.Item):
    file_name = scrapy.Field()
    file_path = scrapy.Field()
    country_code = scrapy.Field()
    report_id = scrapy.Field()
    exchange_market_code = scrapy.Field()
    start_date = scrapy.Field()
    end_date = scrapy.Field()
    language_written_code = scrapy.Field()
    doc_type = scrapy.Field()
    doc_source_url = scrapy.Field()
    is_doc_url_direct = scrapy.Field()
    doc_local_path = scrapy.Field()
    doc_downloaded_timestamp = scrapy.Field()
    is_downloaded = scrapy.Field()
    is_consolidated = scrapy.Field()
    gmt_create = scrapy.Field()
    user_create = scrapy.Field()
    belong_2_type = scrapy.Field()
    object = scrapy.Field()
    type = scrapy.Field()
    number = scrapy.Field()
    title = scrapy.Field()
    publish_date = scrapy.Field()
    related_bond = scrapy.Field()
    company_id = scrapy.Field()


class ShenzhensecuritiesItemS(scrapy.Item):
    bond_code = scrapy.Field()
    security_code = scrapy.Field()
    short_name = scrapy.Field()
    name_origin = scrapy.Field()
    name_en = scrapy.Field()
    security_type = scrapy.Field()
    security_form = scrapy.Field()
    interest_payment_method = scrapy.Field()
    start_interest_date = scrapy.Field()
    end_date = scrapy.Field()
    redemption_date = scrapy.Field()
    repayment_period = scrapy.Field()
    interest_date_description = scrapy.Field()
    ipo_date = scrapy.Field()
    delisting_date = scrapy.Field()
    unit_denomination = scrapy.Field()
    interest_rate_type = scrapy.Field()
    coupon_rate = scrapy.Field()
    interest_rate_start_date = scrapy.Field()
    interest_rate_end_date = scrapy.Field()
    issue_object = scrapy.Field()
    issue_price = scrapy.Field()
    issue_start_date = scrapy.Field()
    issue_end_date = scrapy.Field()
    actual_circulation = scrapy.Field()
    issuance_method = scrapy.Field()
    issuance_fee_rate = scrapy.Field()
    distribution_method = scrapy.Field()
    tender_date = scrapy.Field()
    short_name_sz = scrapy.Field()
    security_form_sz = scrapy.Field()
    interest_payment_method_sz = scrapy.Field()
    start_interest_date_sz = scrapy.Field()
    end_date_sz = scrapy.Field()
    redemption_date_sz = scrapy.Field()
    repayment_period_sz = scrapy.Field()
    interest_date_description_sz = scrapy.Field()
    delisting_date_sz = scrapy.Field()
    unit_denomination_sz = scrapy.Field()
    interest_rate_type_sz = scrapy.Field()
    coupon_rate_sz = scrapy.Field()
    interest_rate_start_date_sz = scrapy.Field()
    interest_rate_end_date_sz = scrapy.Field()
    issue_object_sz = scrapy.Field()
    issue_price_sz = scrapy.Field()
    issue_start_date_sz = scrapy.Field()
    issue_end_date_sz = scrapy.Field()
    actual_circulation_sz = scrapy.Field()
    issuance_method_sz = scrapy.Field()
    issuance_fee_rate_sz = scrapy.Field()
    distribution_method_sz = scrapy.Field()
    tender_date_sz = scrapy.Field()
    exchange_market_code = scrapy.Field()
    country_code_origin = scrapy.Field()
    gmt_create = scrapy.Field()
    user_create = scrapy.Field()
    gmt_update = scrapy.Field()
    user_update = scrapy.Field()

